add content-toggle block
adobecom/express-milo pull request #68
Opened 2024-10-07 19:01 UTC by jrrings

Describe your specific features or fixes

Resolves: [MWPW-143344](https://jira.corp.adobe.com/browse/MWPW-143344)

Test URLs:
- Pre Migration Link: https://adobe.com/express/collaborations
- Before: https://main--express-milo--adobecom.hlx.page/express/collaborations
- After: https://MWPW-143344--express-milo--adobecom.hlx.page/express/collaborations

Additional Test URLs:
- https://MWPW-143344--express-milo--adobecom.hlx.page/express/experiments/ccx0110/education-challenger

2024-10-14 20:04 UTC, fullcolorcoder approved these changes

2024-10-15 13:14 UTC, vhargrave requested changes
I'm having very strange behaviour on this page - https://mwpw-143344--express-milo--adobecom.hlx.page/express/collaborations

when I first of all switch to brands I get a strange jump on the screen. You'll notice it by going to the page, clicking on brands, switching to another content toggle like Print, and clicks on Brands again. 

I'm also seeing that the whole header "Explore by collection" is not visible , whereas it is always visible when switching around on prod

2024-10-16 13:56 UTC, jrrings commented
@vhargrave - Is this what you're talking about? 

https://github.com/user-attachments/assets/c2987208-5791-4e78-8bb4-b1ce59c2717b

2024-10-17 07:56 UTC, vhargrave commented
> * https://MWPW-143344--express-milo--adobecom.hlx.page/express/experiments/ccx0110/education-challenger

@jrrings no, I can't seem to reproduce the weird jumpy behaviour anymore today, which is good I guess. I'm also getting slightly different behaviour on prod than what I had yesterday lol 
whatever the case, your version is working like a pure copy of prod for me today, so all good. I'll approve.

2024-10-17 07:56 UTC, vhargrave approved these changes

2024-10-17 07:56 UTC, merged