Mwpw 143327 app banner
adobecom/express-milo pull request #82
Opened 2024-10-24 18:08 UTC by vhargrave

Resolves: [MWPW-143327](https://jira.corp.adobe.com/browse/MWPW-143327)

To test you'll have to test on mobile. I did a crawl and this is the only live page with the app-banner.

Test URLs:
- Pre Migration Link: https://adobe.com/express/
- Before: https://main--express-milo--adobecom.hlx.page/jp/express/create/advertisement/facebook
- After: https://MWPW-143327-app-banner--express-milo--adobecom.hlx.page/jp/express/create/advertisement/facebook

2024-10-24 20:56 UTC, fullcolorcoder requested changes
Text isn't aligned the same as prod. 

Prod: 
![image](https://github.com/user-attachments/assets/941b2827-511d-40da-8725-9ac76923b4e5)

branch: 
![image](https://github.com/user-attachments/assets/a3c302f6-1da1-4567-8b65-24cadcf8a513)

- What are all the other files for? Are there additional planned changes aside from app banner?

2024-10-24 20:56 UTC, fullcolorcoder commented on express/blocks/app-banner/app-banner.js
> +    debugger;
Debugger

2024-10-24 20:56 UTC, fullcolorcoder commented on express/blocks/app-banner/app-banner.js
> +  const $section = block.closest('.section');
linting

2024-10-28 09:03 UTC, vhargrave commented
> Text isn't aligned the same as prod.
> 
> Prod: ![image](https://private-user-images.githubusercontent.com/7562106/379933711-941b2827-511d-40da-8725-9ac76923b4e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDYzMzYsIm5iZiI6MTczMDEwNjAzNiwicGF0aCI6Ii83NTYyMTA2LzM3OTkzMzcxMS05NDFiMjgyNy01MTFkLTQwZGEtODcyNS05YWM3NjkyM2I0ZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDkwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQyMTNlOWQ2MmFmMTA0YjI5N2ZmNDg4YTBmMjExODhiZTk2NTc4YzQ3YjQzOTdkYmQ0NzY5MWQxYjU5MTM4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-s4oLF9OwHnfEePiPW1iPwQTOL9M8Th0WxJW_-L6P10)
> 
> branch: ![image](https://private-user-images.githubusercontent.com/7562106/379933947-a3c302f6-1da1-4567-8b65-24cadcf8a513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDYzMzYsIm5iZiI6MTczMDEwNjAzNiwicGF0aCI6Ii83NTYyMTA2LzM3OTkzMzk0Ny1hM2MzMDJmNi0xZGExLTQ1NjctOGI2NS0yNGNhZGNmOGE1MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDkwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzMyNjQyNTJlMDA2MmJmM2UzYzFjNTVmZmMxNzhmNzBiMjI5NTc4OGFkMmRlMjBmMmZjZmU0NzAzZmE5ZTdhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6bFjtbploCeqJX1TJcYhr2rONipgt9W4x4JRwXrQQdE)
> 
> * What are all the other files for? Are there additional planned changes aside from app banner?

@fullcolorcoder yeah, I know the text is a bit confusing. I should have written something. The text is getting formatted because of milo's formatting of JP texts. As I've agreed to with the JP team, we'll allow milo to do formatting of any h1-h6 tags, even if they look different. That's what's happening here. 
I've removed the debugger statement thanks! 
Finally, for the files you were seeing, that was because I had branched off the "general-fixes" branch to have a less buggy version of everything. Now that that's merged though, you won't see the changes anymore.

2024-10-28 14:46 UTC, fullcolorcoder approved these changes

2024-10-28 14:46 UTC, merged